export const EVENTS_DATA = 
[
  {
    "id": "",
    "title": "Exclusive: 20% off total bill",
    "description": "1. To celebrate Songkran festival in April, offering 20% off total bill to all 2. This offer is not valid in conjunction with other ongoing promotions, offers, vouchers and discounts and/or privileges.",
    "address": "-",
    "url": "-",
    "postalCode": 138602,
    "longitude": "",
    "latitude": "",
    "ownerId": "2Hcun4C061esCQ62jqTzmDnT9u12",
    "startTime": "2018-04-14T10:00:00Z",
    "endTime": "2018-04-14T17:00:00Z",
    "category": "Food and Beverage"
  },
  {
    "id": "",
    "title": "Exclusive: 20% off total bill",
    "description": "1. To celebrate Songkran festival in April, offering 20% off total bill to all 2. This offer is not valid in conjunction with other ongoing promotions, offers, vouchers and discounts and/or privileges.",
    "address": "-",
    "url": "-",
    "postalCode": 138602,
    "longitude": "",
    "latitude": "",
    "ownerId": "2Hcun4C061esCQ62jqTzmDnT9u12",
    "startTime": "2018-04-16T10:00:00Z",
    "endTime": "2018-04-16T17:00:00Z",
    "category": "Food and Beverage"
  },
  {
    "id": "",
    "title": "Exclusive: 20% off total bill",
    "description": "1. To celebrate Songkran festival in April, offering 20% off total bill to all 2. This offer is not valid in conjunction with other ongoing promotions, offers, vouchers and discounts and/or privileges.",
    "address": "-",
    "url": "-",
    "postalCode": 138602,
    "longitude": "",
    "latitude": "",
    "ownerId": "2Hcun4C061esCQ62jqTzmDnT9u12",
    "startTime": "2018-04-21T10:00:00Z",
    "endTime": "2018-04-21T17:00:00Z",
    "category": "Food and Beverage"
  },
  {
    "id": "",
    "title": "Exclusive: 20% off total bill",
    "description": "1. To celebrate Songkran festival in April, offering 20% off total bill to all 2. This offer is not valid in conjunction with other ongoing promotions, offers, vouchers and discounts and/or privileges.",
    "address": "-",
    "url": "-",
    "postalCode": 138602,
    "longitude": "",
    "latitude": "",
    "ownerId": "2Hcun4C061esCQ62jqTzmDnT9u12",
    "startTime": "2018-04-23T10:00:00Z",
    "endTime": "2018-04-23T17:00:00Z",
    "category": "Food and Beverage"
  },
  {
    "id": "",
    "title": "Exclusive: 20% off total bill",
    "description": "1. To celebrate Songkran festival in April, offering 20% off total bill to all 2. This offer is not valid in conjunction with other ongoing promotions, offers, vouchers and discounts and/or privileges.",
    "address": "-",
    "url": "-",
    "postalCode": 138602,
    "longitude": "",
    "latitude": "",
    "ownerId": "2Hcun4C061esCQ62jqTzmDnT9u12",
    "startTime": "2018-04-28T10:00:00Z",
    "endTime": "2018-04-28T17:00:00Z",
    "category": "Food and Beverage"
  },
  {
    "id": "",
    "title": "Exclusive: 20% off total bill",
    "description": "1. To celebrate Songkran festival in April, offering 20% off total bill to all 2. This offer is not valid in conjunction with other ongoing promotions, offers, vouchers and discounts and/or privileges.",
    "address": "-",
    "url": "-",
    "postalCode": 138602,
    "longitude": "",
    "latitude": "",
    "ownerId": "2Hcun4C061esCQ62jqTzmDnT9u12",
    "startTime": "2018-04-30T10:00:00Z",
    "endTime": "2018-04-30T21:00:00Z",
    "category": "Food and Beverage"
  },
  {
    "id": "",
    "title": "The mouth watering new recipe: Pulled Pork Nachos.",
    "description": "Goruden Singapore introduces its new menu, which will be available on 17 Dec 2016. The mouth watering new recipe: Pulled Pork Nachos. From sweet to superbly savory, nachos will be taken to a new level at our outlet. Through the holiday seasons, our chef will prepare three different types of sauces served in homemade pulled pork for a warm and hearty option. They will include cheesy cheese, wasabi mayo and garlic mayo. For those who prefer a healthier alternative, our nachos are can be served in lettuce fillings.",
    "address": "-",
    "url": "-",
    "postalCode": 119078,
    "longitude": "",
    "latitude": "",
    "ownerId": "2Hcun4C061esCQ62jqTzmDnT9u12",
    "startTime": "2018-04-14T10:00:00Z",
    "endTime": "2018-04-14T21:00:00Z",
    "category": "Food and Beverage"
  },
  {
    "id": "",
    "title": "CRYSTAL JADE KITCHEN",
    "description": "$11.80 Weekday Value Lunch Set (U.P $17.20) – Enjoy 1 Main + 1 Appetiser of your choice (Half Portion). Featuring our Roast Meat Rice or Noodle selection, Hong Kong Noodle and more! Complete your meal with drinks at $2 or soup of the day at $3.80 only!",
    "address": "-",
    "url": "-",
    "postalCode": 129588,
    "longitude": "",
    "latitude": "",
    "ownerId": "2Hcun4C061esCQ62jqTzmDnT9u12",
    "startTime": "2018-04-16T10:00:00Z",
    "endTime": "2018-04-20T21:00:00Z",
    "category": "Food and Beverage"
  },
  {
    "id": "",
    "title": "CRYSTAL JADE KITCHEN",
    "description": "$11.80 Weekday Value Lunch Set (U.P $17.20) – Enjoy 1 Main + 1 Appetiser of your choice (Half Portion). Featuring our Roast Meat Rice or Noodle selection, Hong Kong Noodle and more! Complete your meal with drinks at $2 or soup of the day at $3.80 only!",
    "address": "-",
    "url": "-",
    "postalCode": 129588,
    "longitude": "",
    "latitude": "",
    "ownerId": "2Hcun4C061esCQ62jqTzmDnT9u12",
    "startTime": "2018-04-23T10:00:00Z",
    "endTime": "2018-04-27T21:00:00Z",
    "category": "Food and Beverage"
  },
  {
    "id": "",
    "title": "CRYSTAL JADE KITCHEN",
    "description": "$11.80 Weekday Value Lunch Set (U.P $17.20) – Enjoy 1 Main + 1 Appetiser of your choice (Half Portion). Featuring our Roast Meat Rice or Noodle selection, Hong Kong Noodle and more! Complete your meal with drinks at $2 or soup of the day at $3.80 only!",
    "address": "-",
    "url": "-",
    "postalCode": 129588,
    "longitude": "",
    "latitude": "",
    "ownerId": "2Hcun4C061esCQ62jqTzmDnT9u12",
    "startTime": "2018-04-30T10:00:00Z",
    "endTime": "2018-05-04T21:00:00Z",
    "category": "Food and Beverage"
  },
  {
    "id": "",
    "title": "1 for 1, all drinks",
    "description": "buy one get one free, for all drinks",
    "address": "-",
    "url": "-",
    "postalCode": 117549,
    "longitude": "",
    "latitude": "",
    "ownerId": "2Hcun4C061esCQ62jqTzmDnT9u12",
    "startTime": "2018-04-16T10:00:00Z",
    "endTime": "2018-04-20T21:00:00Z",
    "category": "Food and Beverage"
  },
  {
    "id": "",
    "title": "1 for 1, all drinks",
    "description": "buy one get one free, for all drinks",
    "address": "-",
    "url": "-",
    "postalCode": 117549,
    "longitude": "",
    "latitude": "",
    "ownerId": "2Hcun4C061esCQ62jqTzmDnT9u12",
    "startTime": "2018-04-23T10:00:00Z",
    "endTime": "2018-04-27T21:00:00Z",
    "category": "Food and Beverage"
  },
  {
    "id": "",
    "title": "1 for 1, all drinks",
    "description": "buy one get one free, for all drinks",
    "address": "-",
    "url": "-",
    "postalCode": 117549,
    "longitude": "",
    "latitude": "",
    "ownerId": "2Hcun4C061esCQ62jqTzmDnT9u12",
    "startTime": "2018-04-30T10:00:00Z",
    "endTime": "2018-05-04T21:00:00Z",
    "category": "Food and Beverage"
  }
]